### ISSUE TITLE
Remover dados de contato da pagina de vaga

### ISSUE THREAD

**Issue by dvinciguerra** [builtinruby/builtinruby#8]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/114177/95520300-5675ac80-099d-11eb-9dac-da3a7eedb56d.png">

A pagina de detalhes das vagas contém informações de contato que não são mais utilizada e ficam sempre visíveis em branco

### Solução

Precisamos remover esta linha dos detalhes da vaga.

### O que esperamos?

Apenas a remoção da linha de contato dos detalhes da vaga oras ¯\\_(ツ)_/¯.

**Comment by guilhermeorcezi** [comment]
Posso fazer essa issue?

**Comment by dvinciguerra** [comment]
Claro... obrigado pela ajuda! =)
